const a = 3
const c = "ahfiuhiuhiuehgiuehgurieghieruhgeiurhgiurehgiurehgiurhgiuerhgiruehguierhgireuhgieughiueghriueghieughruigheiughruigheuihgiurehgieurhgeuihgieughueirghiuergheuihghguerihguirehguieruhgiuehgie"
console.log(a, c)